import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "./auth-provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ['latin'],
  weight: ["200","300", "400", "500", "600", "700"] 
});

export const metadata: Metadata = {
  title: "Vehicle Maintenance System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <AuthProvider>
        {children}
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
